# Registry Service
# Se apps/auth/base/service.yaml for detaljerede kommentarer

apiVersion: v1
kind: Service
metadata:
  name: registry    # Tilgås via "http://registry:8080"
spec:
  selector:
    app: registry
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30501
  type: NodePort
