# Kustomize overlay for relay i dev miljø
# Se apps/auth/overlays/dev/kustomization.yaml for detaljerede kommentarer

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: ghcr.io/mtbonde/hagi-relayservice
    newName: ghcr.io/mtbonde/hagi-relayservice
    newTag: 0.5.4 # {"$imagepolicy": "flux-system:relay"}
